### ISSUE TITLE
Don't save gems to vendor/cache

### ISSUE THREAD

**Issue by awead** [psu-stewardship/etda#19]
Maybe, maybe not? We don't do this with other projects and wonder if there's a reason why we're doing do here.

**Comment by EricDurante** [comment]
Hi Adam,

Including copies of the gems in the project repository is our standard practice. We do it primarily to remove the dependency on a remote gem server during deployment for the sake of reliability and (theoretically) better security. For example, we want to avoid the scenario where we're not able to deploy an application at a critical time because rubygems.org happens to be down - or the scenario where rubygems.org gets hacked, and some malicious code gets added to a gem that we're depending on, and the gem gets deployed to production before we can catch it.

It's by no means necessary, and including the gem source with the project has its downsides too - larger repository, slower deployments, etc. So we're happy to leave it up to you as to what makes the most sense for your team.

Eric

**Comment by woods** [comment]
Actually packaging won't slow down deployments -- capistrano detects `vendor/cache` and bundles with `--local` so that it doesn't even need to contact rubygems.org. Some argue packaging actually speeds up deployment, and I feel like I've noticed the same thing, but I haven't actually confirmed/tested it. 

So you do gain guaranteed consistency, reduced dependencies during deployment, and some measure of security, with the tradeoff of larger repo size.

**Comment by EricDurante** [comment]
Oh, nice - I didn't realize that. I guess there's not really much of a downside then.

**Comment by awead** [comment]
Yeah, the only downside I noticed was a large repo, which took more time to push up, but other than that, it makes sense.

**Comment by woods** [comment]
Ah yes, there's one more occasional downside. When you bundle a new version
of libv8 on your Mac, you have to remember to include a copy of the linux
version for the servers as well.

```
gem fetch libv8 --version 3.16.14.7 --platform x86_64-linux
```

So to summarize:

Pros:
- More resilient against Rubygems outage / slowness
- Smaller exposure window to rogue/hacked gems
- Assurance against clumsy gem authors that push fixes to the same version
number (we've seen this)
- Assurance against minor gem authors un-publishing their gems/versions
(we've seen this)
- All dependent code is versioned with the repo
- Maybe faster deploys

Cons:
- Larger repo makes for slower initial clone, slower push/pull of massive
gem upgrades
- You have to maintain the linux version of libv8
- More disk space on server / laptop

I think it's going to come down to preference. West Arete settled on
packaging because it gave us the warm-and-fuzzies to have all of the
dependencies locked in under version control. It means we only look to
Rubygems as a download source, instead of using it as an authority for
whether we're all running the same copy of the code or not. That philosophy
sits well with us, and made it worth the minor tradeoffs. I'm sure that
others would feel that this approach is too paranoid and would rather
optimize other efficiencies.

Cheers, Adam and Eric! Thanks for the discussion.



On Mon, Nov 16, 2015 at 7:59 AM, Adam Wead <notifications@github.com> wrote:

> Yeah, the only downside I noticed was a large repo, which took more time
> to push up, but other than that, it makes sense.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/psu-stewardship/etda/issues/19#issuecomment-157021936>
> .
>



-- 
Scott Woods
West Arete
http://westarete.com/
scott@westarete.com
814-753-4951

**Comment by hectorcorrea** [comment]
:+1:
